use_frameworks!
platform :ios, '11.0'

target 'Afflatus_Example' do
  pod 'Afflatus/Core', :path => '../'

  target 'Afflatus_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
